### ISSUE TITLE
【组员报到】《老人与海》翻译小组启动啦!

### ISSUE THREAD

**Issue by lucy201703** [lucy201703/TranslatingForWriting#1]
再不来翻译小组报到，春天就过去了，2018年就没了！

正如仓库标题TranslatingForWriting，此次共同学习的目的是在翻译实践中提高语言鉴赏和表达能力。为了达到这一目的，我们需要考虑以下几个问题：

## 选材与目的
首先是选材，我们选择了开智学堂认知写作学课程屡屡提及，倍受阳老师推崇的语言经典海明威的《老人与海》，且本书有余光中和张爱玲两位中文作家的两个译本。以自身的翻译实践为基础，对照源本和译本的阅读，既能验证自己对英文原著的理解和品位，也能品析三位作家对同一主题的表达风格，以及英汉语言异曲同工的微妙。最重要的是通过翻译实践，看到自己与作家们清晰的差距，知道他们好在哪我们差在哪，借助他们的文字看到他们眼中的美，从而提升我们对美的领悟和表达能力。

## 翻译与赏析
《老人与海》这本书很薄，花一个月时间转换成中文文字并不难。但如果这个翻译练习大部分时间只是花在文字翻译本身，我们就浪费了三位作家的才华。所以我们至少要花同等的时间赏析三个文本的美，还至少要花同等的时间教自己怎么做到这种美。如果这些美令你念念不忘，你还需要花时间背诵你喜欢的片段。因此，翻译《老人与海》，我们至少需要做好以下方面：

1. 在没有中文译文的辅助下赏析原文；
- 翻译成你自己的译文作品；
- 对比赏析余光中和张爱玲的两个译本；
- 总结自己的译文缺陷和改善方法；
- 小组讨论共享，在鲜活的同侪见解和问题碰撞中相互学习巩固；

第一步和第三步最好形成书面笔记，或模仿撰写片段，用别人的文本教自己创作；
第二步强调“译文作品”，是不光把意思说出来证明我们读懂了，还要努力译出自己理解到的美，就像创作自己的作品一样，以我们自己的理解角度以及对文字的创造力再现原文图景；
第四步要找到自己明晰的进步路径，在美和进步中积淀翻译和写作的趣味；
第五步小组讨论，升华前面四步的努力，从伙伴身上学习最大化学习效益。

## 小组学习
所谓小组学习，除了建立仓库让大家在同一个平台提交各自的翻译作品和思考之外，更重要的是如何让大家的学习碰撞出思想火花。我想，大家眼中的翻译学习小组绝不是到截至时间急急忙忙提交任务，然后顺便在github里友好留言。在相互监督和鼓励之外，我们还要借助伙伴的力量更快地进步，借助伙伴的视角对美的作品有更深的洞察力，借助伙伴的思路对笔下的文字有更主动的创造力。

怎么让我们的学习交流碰撞起来生出火花呢？我有以下想法供大家参考，也欢迎大家修正和补充：

在研一的时候，笔译老师每周布置一篇短小的文学作品，同学们翻译完后附上赏析。每周由一位同学汇总全班的作品，总结提炼大家的作品和赏析，在课上与大家分享。

虽然以前因为学习思维闭塞，同学们观点保守，没有从这种学习模式受益太多。但把这种学习方式运用到我们今天的四人学习小组，应该是不错的尝试。大家自主学习积极性高，不受身份限制思维开阔，且人数少适合深入交流。每周由一人轮流主持当周翻译，负责当周翻译进度把控，主持Zoom会议等引领大家讨论交流，总结当周的翻译成果，提升下周的翻译起点。

除了提升本次学习的互动交流，这种学习模式的另一个重要意义是：我们一起探索一种有效的互助小组学习模式，在实践中不断改进完善，把学习变成一件更轻松更快乐的事情，并把这种小组模式运用到今后的日常学习中。

## 学习节奏
单翻译这个手工体力活，一个月翻译完《老人与海》不成问题，加上至少同等时间的文本赏析和翻译比对总结，整个翻译周期最好拉伸到2-3个月。相当于我们把《老人与海》这本书分成8-12个篇章，每周完成一个篇章的学习。大家对比开智学堂每周出品一篇千字文的节奏，可略知完成每周翻译的强度：

- 刷卡包看视频VS查单词查背景理解句子篇章
- 快写千字文VS快译一个篇章
- 慢改千字文VS慢改一个篇章
- 赏析同学作品VS赏析参考译本和伙伴译本（最好形成笔记）
- 迭代千字文VS迭代译本（进阶要求）
- 每周教练Zoom分享VS每周Zoom讨论总结本周翻译

## 待解决问题
- 如何划分段落篇章
这个是不是大家一起在预备周开展，一起读全文划分主题，还是简单按篇幅划分？
- 确定学习周期
2018年4月1日-4月7日预备周，整个学习周期是2个月还是3个月，要依据我们划分的主题确定，还是依据周期划分主题？

## 组员报到
大家在下面留下脚印，翻译小组就正式启动了。

```
- 名号：李星星
- GitHub：lucy201703
- 学习要求：像迭代一篇千字文一样翻译每一个篇章；输出每周学习笔记。
- 学习目标：了海明威、余光中和张爱玲的文章风格；品读英汉语言的美和异同；每周总结一个适合自己的语言表达技巧。
- 活动期待：在伙伴们的作品和思考中发现别开生面的见解。
- 对待决问题看法：请补充。
- 疑惑：请补充。
```

**Comment by jason2960** [comment]
```
- 名号：阿杰
- GitHub：jason2960
- 学习要求：翻译文章，记录学习过程，不断反馈，迭代，输出每周学习笔记。
- 学习目标：了解海明威、余光中和张爱玲的文章风格；品读英汉语言的美和异同；每周总结一个适合自己的语言表达技巧。
- 活动期待：在伙伴们的作品和思考中发现别开生面的见解。
- 对待决问题看法：作业沉淀，沟通主要是以GitHub为主吗？
- 疑惑：我觉得有必要先通读一遍英文版本的小说，在动手翻译。
```

**Comment by sumin1123** [comment]
- 名号：苏敏
- GitHub：sumin1123
- 学习要求：自行翻译、对比张、余译作、分析修正。
- 学习目标：完成全本翻译，对分析修正进行记录。
- 活动期待：观摩小伙伴们的学习方法。
- 对待决问题看法：请补充。
- 疑惑：
    - 暂时不参与中文返回英文的步骤，因为时间有限，先完成英译中部分；
    - 8 周的节奏不太适合我的时间安排，我将放缓至 16 周；因为我的实际检测，第一段的翻译，我用了 130 分钟，时间资源要求很多。

**Comment by Louie5** [comment]
名号：Louie
GitHub：Louie5
学习要求：执行每日最小行动，借助同侪放大进步。
学习目标：翻译全本老人与海，习得更多写作技巧。
活动期待：升级写作技能，小伙伴的独特见解。
对待决问题看法：请补充。
疑惑：时间是否可以适当放宽?
