### ISSUE TITLE
《老人与海》翻译ch1任务提交处

### ISSUE THREAD

**Issue by lucy201703** [lucy201703/TranslatingForWriting#3]
预备周和阿杰线下交流《老人与海》翻译执行细节之后，迫不及待要开始这场翻译之旅了！

## 本周学习安排

- **Fork仓库**
还没有 fork `TranslationForWriting`仓库的伙伴记得fork一下，生成你的个人翻译仓库。

- **领取任务**
点击仓库code，打开ch1的 source-text文件，就可以看到本周任务啦。大概2500词左右，不影响翻译的前提下不建议浪费过多时间查询单词和背景，毕竟2500词（后面还有更长的篇幅）光翻译和比读就得不少时间。切记快写慢改和最小行动，我们的**最小行动是翻译和文本赏析**，有余力者可进阶回译和背诵优美选段。

- **提交任务截止时间**
 1wd6（180414）20:42 前提交到本 ch1 任务 Issue 下。

- **讨论交流时间**
 1wd7（180415）20:00-21:00（具体可调整）zoom会议或微信群聊集中讨论，同时欢迎随时在微信群抛砖引玉。

## 作业提交说明

1. **上传你的作业和笔记**：将作业上传到自己仓库 `YourGitHub ID/TranslatingForWriting` 的 `ch1` 目录下：

		├── ch1
		│   ├── 1-source-text.md 此文档为英文原稿，可记录查询单词和背景资料
		│   ├── 2-translation.md 在此文档撰写翻译文本
		│   ├── 3-appreciation.md 在此文档撰写译本比读和赏析
		│   ├── 4-back-translation.md 在此文档撰写回译文本
        │   ├── 5-experience.md 在此文档记录本周体验（三言两语随手记好过什么都不写噢）

 2. **在本 Issue 下回复你的作业**： 回复模板参考以下格式
  
    ```
    [你的名号]完成 ch1 任务啦

    - 任务提交
        - translation：地址 
        - appreciation：地址 
        - back-translation：地址
        - experience：地址
    - 分享或疑惑
    ```
欢迎不断迭代任务成果。遇到困难，一定及时在队内，或在课程仓库发 Issue 探讨哦。

**Comment by lucy201703** [comment]
~~ni~~

**Comment by lucy201703** [comment]
老人把收着帆的桅杆靠在墙上，男孩把盒子和其它渔具放在旁边。~~桅杆几乎占据棚屋一间房的长度~~桅杆几乎和这单间的棚屋一样长（@吴**准确**&**简洁**）。~~棚屋的材料是坚硬的王棕budshieds，叫“海鸟粪”~~棚屋用叫做“guano（西班牙语）”的王棕坚韧的护芽棕皮做成（@吴**流畅自然**），里面有一张床，一张桌子，一把椅子和泥土地板上一处用来烧炭的地方。~~牢固的纤维状纤维结实的海鸟粪的叶子平铺重叠,筑成棕色的墙~~在这用纤维结实的被展平的棕叶叠盖而成的褐色墙壁上（@吴**流畅自然**），~~墙上~~挂着一幅彩色的耶稣圣心画像和一幅科布雷圣女画像.这些是他妻子的遗物。过去墙上挂着他妻子的浅色照片，但他拿下来了，看见照片使他感到~~孤单~~太孤单（**漏译**）。照片放在角落的架子上，压在他干净的T恤下。

**Comment by lucy201703** [comment]
【星星】完成 ch1 任务啦

- 任务提交
    - translation：[https://github.com/lucy201703/TranslatingForWriting/blob/9082f15828ab390635d665dd9e0e047f803e1fdb/ch1/2-translation.md](地址)
    - appreciation：[https://github.com/lucy201703/TranslatingForWriting/blob/master/ch1/2-translation.md](地址) 
    - back-translation：地址
    - experience：地址
    - review cards：[https://github.com/lucy201703/TranslatingForWriting/blob/master/ch1/6-review-cards.md](地址)
- 分享或疑惑

**Comment by jason2960** [comment]
【阿杰】完成 ch1 任务啦

    - 任务提交
        - translation：[地址](https://github.com/jason2960/TranslatingForWriting/blob/master/ch1/2-translation.md)
        - appreciation：[地址](https://github.com/jason2960/TranslatingForWriting/blob/master/ch1/3-appreciation.md)
        - back-translation：[地址]()
        - experience：[地址](https://github.com/jason2960/TranslatingForWriting/blob/master/ch1/5-experience.md)
    - 分享或疑惑
